config/routes.rb
Rails.application.routes.draw do
  constraints subdomain: "app" do
    get "static_pages/landing_page"
  end
  # get 'static_pages/pricing', constraints: {subdomain: 'admin'}
  # get 'pricing', to: 'static_pages#pricing', constraints: {subdomain: 'admin'}
  constraints subdomain: "api" do
    scope module: "api" do
      get "static_pages/features"
    end
  end
  # get 'cars', to: 'cars#index'
  # post 'cars', to: 'cars#create'
  # get 'cars/new', to: 'cars#new', as: :new_car
  # get 'cars/:id/edit', to: 'cars#edit', as: :edit_car
  # get 'cars/:id', to: 'cars#show', as: :car
  # put 'cars/:id', to: 'cars#update'
  # patch 'cars/:id', to: 'cars#update'
  # delete 'cars/:id', to: 'cars#destroy'
  # post 'leads/create', to: 'leads#create', as: :create_a_lead

  get "static_pages/landing_page"
  root to: "static_pages#landing_page"
  get "stats", to: "static_pages#stats" # total stats for the superadmin

  get "booking", to: "booking#index"
  get "/booking/:id", to: "booking#show", as: :booking_show
  match "/booking/:id" => "booking#create", :via => [:post], :as => :create
  get "/booking/:id/new", to: "booking#new", as: :new_booking

  # *MUST* come *BEFORE* devise's definitions (below)
  as :user do
    match "/user/confirmation" => "confirmations#update", :via => :put, :as => :update_user_confirmation
  end

  devise_for :users, controllers: {
    registrations: "registrations",
    confirmations: "confirmations",
    sessions: "milia/sessions",
    passwords: "milia/passwords"
  }

  resources :users, only: [:destroy, :edit, :update]
  resources :members do
    get :calendar_list, on: :collection
    member do
      delete :delete_avatar
      get :calendar
    end
  end
  resources :after_signup_wizard

  resources :leads do
    resources :booking_wizard, controller: "leads/booking_wizard"
    member do
      patch :create_client_from_lead
    end
  end

  # edit tenant info
  match "/settings/show" => "tenants#show", :via => :get
  match "/settings/edit" => "tenants#edit", :via => :get, :as => :edit_tenant
  match "/settings/update" => "tenants#update", :via => [:put, :patch], :as => :update_tenant
  match "/plan/edit" => "tenants#edit_plan", :via => :get, :as => :edit_plan

  # contacts google import
  get "contacts/import"
  get "contacts/add_all"
  get "/contacts/:provider/contact_callback" => "contacts#import"
  get "/contacts/failure" => "contacts#failure"
  resources :contacts, except: [:destroy, :create, :new, :edit, :update] do
    member do
      patch :create_client_from_contact, :fill_missing_client_data
    end
  end

  resources :clients do
    get :debtors, :no_gender, :bday_today, :no_events, :untagged, on: :collection
    resources :comments
  end

  resources :service_categories
  resources :services

  resources :locations
  resources :workplaces, only: [:show, :index, :destroy]

  resources :events do
    resources :transactions, except: [:edit, :update]
    get :close, :today, :tomorrow, on: :collection
    member do
      patch :create_duplicate
      patch :mark_planned
      patch :mark_confirmed
      patch :mark_member_cancelled
      patch :mark_client_cancelled
      patch :mark_no_show
      patch :mark_no_show_refunded
      patch :send_email_to_client
      patch :send_email_to_members
    end
  end

  resources :transactions, except: [:edit, :update]
  resources :cash_accounts, except: [:show]

  get "calendar", to: "dashboard#calendar"
  get "activity", to: "dashboard#activity"

  get "dashboard/client_stats"
  get "dashboard/member_stats"
  get "dashboard/event_stats"
  get "dashboard/transaction_stats"
  get "dashboard/lead_stats"
  get "dashboard/member_salary"
  namespace :charts do
    get "monthly_events"
    get "finances_client_due_price_per_month"
    get "members_jobs_per_member_per_month_quantity"
    get "members_confirmed_client_price_per_month"
    get "members_confirmed_earnings_per_month"
    get "transactions_per_day"
    get "transactions_per_month"
    get "events_per_day"
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  include Pagy::Backend

  def activity
    @pagy, @activities = pagy(PublicActivity::Activity.order("created_at DESC").where(tenant_id: Tenant.current_tenant.id))
  end

  def calendar
    redirect_to calendar_list_members_path
  end

  def client_stats
    authorize Tenant, :show?
  end

  def member_stats
    authorize Tenant, :show?
    @members = Member.all
  end

  def member_salary
    authorize Tenant, :show?
    @members = Member.all # for select
    if params.has_key?(:select)
      @start_date = (params[:select][:year] + "-" + params[:select][:month] + "-" + 0o1.to_s).to_datetime.beginning_of_month
      @end_date = @start_date.end_of_month
      @member = params[:member]

      @jobs = Job.joins(:event, :service, service: :service_category, event: :client).where(events: {starts_at: @start_date..@end_date}).where(member_id: @member).order(starts_at: :asc)
      # did not try this
      # @jobs = Job.where('starts_at BETWEEN ? AND ?', @selected_date.beginning_of_day, @selected_date.end_of_day)

      @member_select = Member.where(id: @member) # for productivity

      # confirmed
      @confirmed_job_q = @jobs.where(events: {status: ["confirmed", "no_show_refunded"]}).count
      @confirmed_hours_worked = @jobs.where(events: {status: ["confirmed", "no_show_refunded"]}).map(&:service_duration).sum / 60.to_d
      @total_confirmed_earnings = @jobs.where(events: {status: ["confirmed", "no_show_refunded"]}).map(&:client_due_price_cents).sum
      @total_confirmed_expences = @jobs.where(events: {status: ["confirmed", "no_show_refunded"]}).map(&:member_due_price_cents).sum
      # cancelled
      @lost_job_q = @jobs.where(events: {status: ["client_cancelled", "member_cancelled", "no_show"]}).count
      @lost_hours_worked = @jobs.where(events: {status: ["client_cancelled", "member_cancelled", "no_show"]}).map(&:service_duration).sum / 60.to_d
      @total_lost_earnings = @jobs.where(events: {status: ["client_cancelled", "member_cancelled", "no_show"]}).map(&:client_price_cents).sum
      @total_lost_expences = @jobs.where(events: {status: ["client_cancelled", "member_cancelled", "no_show"]}).map(&:member_price_cents).sum
    else
      @jobs = Job.joins(:event, :service, service: :service_category, event: :client).where(events: {starts_at: Time.now.beginning_of_month..Time.now.end_of_month}).where(member_id: 0)
    end
  end

  def event_stats
    authorize Tenant, :show?
    # average paycheck
    @average_confirmed_earnings = Job.joins(:event).where(events: {status: ["confirmed", "no_show_refunded"]}).average(:client_due_price).to_i / 100
    if params.has_key?(:select)
      @start_date = (params[:select][:year] + "-" + params[:select][:month] + "-" + 0o1.to_s).to_datetime
      @end_date = @start_date.end_of_month
      @events = Event.where("starts_at BETWEEN ? AND ?", @start_date, @end_date)
    else
      @events = Event.where("starts_at BETWEEN ? AND ?", Time.now.beginning_of_month, Time.now.end_of_month)
    end
  end

  def transaction_stats
    authorize Tenant, :show?
    if params.has_key?(:select)
      @start_date = (params[:select][:year] + "-" + params[:select][:month] + "-" + 0o1.to_s).to_datetime.beginning_of_month
      @end_date = @start_date.end_of_month
      @transactions = Transaction.where("created_at BETWEEN ? AND ?", @start_date, @end_date)
    else
      @transactions = Transaction.where("created_at BETWEEN ? AND ?", Time.now.beginning_of_month, Time.now.end_of_month)
    end
  end

  def lead_stats
    authorize Tenant, :show?
    @leads = Lead.all
  end
end

app/views/dashboard/_activity.haml
.card
  .card-header
    %h5.float-left
      .fa.fa-bell
      %b= t("dashboard.activity.activity")
  %ul.list-group.list-group-flush
    - @activities.each do |a|
      %li.list-group-item
        /= a.id
        /= a.tenant_id
        #{l(a.created_at, format: "%d/%b/%Y %H:%M")}
        (#{time_ago_in_words a.created_at} #{t('.ago')})
        - if a.owner.present? && a.owner.member
          = link_to a.owner.to_s, member_path(a.owner.member.id)
        %span{:class => "fa fa-#{a.key.match(/\.(.*)/)[1]}"}
      
        = a.key
        - if a.trackable
          - unless a.trackable_type == 'Comment'
            = link_to a.trackable, a.trackable
          - else
            = link_to a.trackable.commentable, a.trackable.commentable
          - if a.parameters.present?
            /= a.parameters.empty?
            - unless a.parameters == "{}"
              - unless a.trackable_type == 'Comment'
                = status_label(a.parameters[:status])
              - else
                .card-header
                  .font-weight-light.font-italic= a.parameters[:content]
        - else
          which has since been removed
        /= a.trackable_type
        /= a.trackable_id

app/views/dashboard/activity.haml
= render 'dashboard/activity'
%p
.container.table-responsive
  = will_paginate @activities, renderer: WillPaginate::ActionView::BootstrapLinkRenderer

app/views/dashboard/activity.html.haml
= render 'dashboard/activity'
%p
.container.table-responsive
  != pagy_bootstrap_nav(@pagy)

app/views/dashboard/calendar.haml
/- set_var 'events', @events.map{|e| {title: e.client.full_name.to_s + " (" + e.jobs.collect{|r| r.service.name}.join(",").to_s+")", start: e.starts_at, end: e.ends_at, url: event_path(e), color: e.status_color}}
/- set_var 'jobs', Job.all.map{|e| {title: e.event.client.full_name.to_s + "/" + e.service.name.to_s + " (" + e.member.full_name.to_s + " )", start: e.event.starts_at, end: e.event.ends_at, url: event_path(e.event), color: e.event.status_color}}
/- set_var 'jobs', @jobs.map{|e| {title: e.event.client.full_name.to_s + "/" + e.service.name.to_s + " (" + e.member.full_name.to_s + " )", start: e.event.starts_at, end: e.event.ends_at, url: event_path(e.event), color: e.event.status_color}}
/- set_var 'resources', Member.where(id: @member.id).map{|z| {id: z.id, title: z.last_name.to_s}}
/- set_var 'events', @jobs.map{|e| {title: e.event.client.full_name.to_s + "/" + e.service.name.to_s, resourceId: e.member_id.to_s, start: e.event.starts_at, end: e.event.ends_at, url: event_path(e.event), color: e.event.status_color}}

/BELOW WORKS OK
- set_var 'locale', Tenant.current_tenant.locale
- set_var 'resources', @members.map{|z| {id: z.id, title: z.short_name.to_s}}
- set_var 'events', @jobs.map{|e| {id: e.id, title: e.event.client.full_name.to_s + "/" + e.service.name.to_s, resourceId: e.member_id.to_s, start: e.event.starts_at, end: e.event.ends_at, url: event_path(e.event), color: e.event.status_color}}
/- set_var 'events', @events.map{|e| {resourceIds: e.jobs.collect{|r| r.member_id}, title: e.client.full_name.to_s + " (" + e.jobs.collect{|r| r.service.name}.join(",").to_s+")", start: e.starts_at, end: e.ends_at, url: event_path(e), color: e.status_color}}

.row
  .col-lg-9
    #event_calendar
    %p
  .col-lg-3
    #datepicker
/%br

app/views/dashboard/client_stats.html.haml
.text-center
  %h5= t('.client_stats')
.row
  .col-lg-12
    .card
      .card-header
        .fa.fa-chart-line
        = t('.created_per_month')
      .card-body
        = line_chart Client.group_by_month(:created_at).count, download: true
    %p
.row
  .col-lg-12
    .card
      .card-header
        .fa.fa-chart-line
        = t('.client_birthdays_per_year')
      .card-body
        = line_chart Client.group_by_month(:date_of_birth).count, download: true
    %p
.row
  .col-lg-6
    .card
      .card-header
        .fa.fa-chart-line
        = t('.gender_popularity')
      .card-body
        = pie_chart Client.group(:gender).count, download: true
    %p
  .col-lg-6
    .card
      .card-header
        .fa.fa-chart-line
        = t('.lead_source_popularity')
      .card-body
        = pie_chart Client.group(:lead_source).count, download: true
    %p

app/views/dashboard/clients.haml
.text-center
  %h5= t('.client_stats')
.row
  .col-lg-12
    .card
      .card-header
        .fa.fa-chart-line
        = t('.clients_registered_per_month')
      .card-body
        = line_chart Client.group_by_month(:created_at).count, download: true
    %p
.row
  .col-lg-12
    .card
      .card-header
        .fa.fa-chart-line
        = t('.client_birthdays_per_year')
      .card-body
        = line_chart Client.group_by_month(:date_of_birth).count, download: true
    %p
.row
  .col-lg-6
    .card
      .card-header
        .fa.fa-chart-line
        = t('.status_popularity')
      .card-body
        = pie_chart Client.group(:status).count, download: true
    %p
  .col-lg-6
    .card
      .card-header
        .fa.fa-chart-line
        = t('.gender_popularity')
      .card-body
        = pie_chart Client.group(:gender).count, download: true
    %p
  .col-lg-6
    .card
      .card-header
        .fa.fa-chart-line
        = t('.lead_source_popularity')
      .card-body
        = pie_chart Client.group(:lead_source).count, download: true
    %p

app/views/dashboard/events.haml
.text-center
  %h5= t('.event_stats')
%ul#myTab.nav.nav-tabs{:role => "tablist"}
  %li.nav-item
    %a#zero-tab.nav-link.active{"aria-controls" => "zero", "aria-selected" => "true", "data-toggle" => "tab", :href => "#zero", :role => "tab"}
      = t('.per_day')
  %li.nav-item
    %a#first-tab.nav-link{"aria-controls" => "first", "aria-selected" => "true", "data-toggle" => "tab", :href => "#first", :role => "tab"}
      = t('.per_month')
  %li.nav-item
    %a#second-tab.nav-link{"aria-controls" => "second", "aria-selected" => "false", "data-toggle" => "tab", :href => "#second", :role => "tab"}
      = t('.other_stats')
#myTabContent.tab-content
  #zero.tab-pane.fade.show.active{"aria-labelledby" => "zero-tab", :role => "tabpanel"}
    %p
    = form_tag dashboard_events_path, method: :get do
      - if params.has_key?(:select)
        = select_month(@start_date, {use_two_digit_numbers: true, prefix: 'select'},{:field_name => 'month', :id => 'start-month', onchange: 'this.form.submit()'})
        = select_year(@start_date, {:start_year => DateTime.now.year,:end_year => Tenant.current_tenant.created_at.year, prefix: 'select'},{:field_name => 'year', :id => 'start-year', onchange: 'this.form.submit()'})
        = link_to t('.current_month'), dashboard_events_path, class: "btn  btn-sm btn-secondary"
      - else
        = select_month(Date.today, {use_two_digit_numbers: true, prefix: 'select'},{:field_name => 'month', :id => 'start-month', onchange: 'this.form.submit()'})
        = select_year(Date.today, {:start_year => DateTime.now.year,:end_year => Tenant.current_tenant.created_at.year, prefix: 'select'},{:field_name => 'year', :id => 'start-year', onchange: 'this.form.submit()'})
      /= submit_tag("Search", :id=>"button", :class=>"Test", :name=>"submit")
    %p
    .row
      .col-lg-6
        .card
          .card-header
            .fa.fa-chart-line
            = t('.confirmed_event_price_per_day')
        %table.table.table-sm.table-bordered
          %tbody
            - @events.is_confirmed.group_by_day(:starts_at).sum("event_due_price/100").each do |k, v|
              %tr
                %td= k.strftime('%d/%m/%Y')
                %td= v
                /%td= number_to_currency(v, unit: "#{Tenant.current_tenant.default_currency.upcase}", format: "%n %u")
        %p
      .col-lg-6
        .card
          .card-header
            .fa.fa-chart-line
            = t('.confirmed_event_price_per_day')
          .card-body
            /= bar_chart charts_events_per_day_path
            = line_chart @events.is_confirmed.group_by_day(:starts_at).sum("client_price/100")
  #first.tab-pane.fade.show{"aria-labelledby" => "first-tab", :role => "tabpanel"}
    %p
    .row
      .col-lg-12
        .card
          .card-header
            .fa.fa-chart-line
            = t('.events_per_month_quantity')
          .card-body
            = column_chart charts_monthly_events_path, download: true
    %p
    .row
      .col-lg-12
        .card
          .card-header
            .fa.fa-chart-line
            = t('.unique_clients_per_month_quantity')
          .card-body
            = column_chart Event.group_by_month(:starts_at, format: "%b %Y").distinct.count('client_id'), download: true
    %p
    .row
      .col-lg-12
        .card
          .card-header
            .fa.fa-chart-line
            = t('.confirmed_event_price_per_month')
          .card-body
            = column_chart Event.is_confirmed.group_by_month(:starts_at).sum("client_price/100")
  #second.tab-pane.fade{"aria-labelledby" => "second-tab", :role => "tabpanel"}
    %p
    .row
      .col-lg-6
        .card
          .card-header
            .fa.fa-chart-line
            = t('.status_popularity')
          .card-body
            = pie_chart Event.group(:status).count, download: true
        %p
      .col-lg-6
        .card
          .card-header
            .fa.fa-chart-line
            = t('.location_popularity')
          .card-body
            = pie_chart Event.joins(:location).group(:'locations.name').count, download: true
        %p
      .col-lg-6
        .card
          .card-header
            .fa.fa-chart-line
            = t('.service_popularity')
          .card-body
            = pie_chart Job.joins(:service).group(:'services.name').count, download: true
      .col-lg-6
        .card-header.bg-default
          %i.fa.fa-dollar-sign
          = number_to_currency(@average_confirmed_earnings, :unit => "")
          %div 
            %b= t('.average_confirmed_check')
%br

app/views/dashboard/expences.haml
.text-center
  %h5= t('.expence_stats')
%ul#myTab.nav.nav-tabs{:role => "tablist"}
  %li.nav-item
    %a#zero-tab.nav-link.active{"aria-controls" => "zero", "aria-selected" => "true", "data-toggle" => "tab", :href => "#zero", :role => "tab"}
      = t('.per_day')
  %li.nav-item
    %a#first-tab.nav-link{"aria-controls" => "first", "aria-selected" => "true", "data-toggle" => "tab", :href => "#first", :role => "tab"}
      = t('.per_month')
#myTabContent.tab-content
  #zero.tab-pane.fade.show.active{"aria-labelledby" => "zero-tab", :role => "tabpanel"}
    %p
    = form_tag dashboard_expences_path, method: :get do
      - if params.has_key?(:select)
        = select_month(@start_date, {use_two_digit_numbers: true, prefix: 'select'},{:field_name => 'month', :id => 'start-month', onchange: 'this.form.submit()'})
        = select_year(@start_date, {:start_year => DateTime.now.year,:end_year => Tenant.current_tenant.created_at.year, prefix: 'select'},{:field_name => 'year', :id => 'start-year', onchange: 'this.form.submit()'})
        = link_to t('.current_month'), dashboard_expences_path, class: "btn  btn-sm btn-secondary"
      - else
        = select_month(Date.today, {use_two_digit_numbers: true, prefix: 'select'},{:field_name => 'month', :id => 'start-month', onchange: 'this.form.submit()'})
        = select_year(Date.today, {:start_year => DateTime.now.year,:end_year => Tenant.current_tenant.created_at.year, prefix: 'select'},{:field_name => 'year', :id => 'start-year', onchange: 'this.form.submit()'})
    %p
    .row
      .col-lg-6
        .card
          .card-header
            .fa.fa-chart-line
            = t('.expences_per_month')
        .card
          .card-header
            %b= t('.quantity') + ":"
            = @expences.count
            %b= t('.amount') + ":"
            = @expences.sum("amount/100")
        %table.table.table-sm.table-bordered
          %tbody
            - @expences.group_by_month(:created_at).sum("amount/100").each do |k, v|
              %tr
                %td= k.strftime('%m/%Y')
                %td= v
        %p
      .col-lg-6
        .card
          .card-header
            .fa.fa-chart-line
            = t('.expence_types')
          .card-body
            = pie_chart @expences.group(:expendable_type).count, download: true
  #first.tab-pane.fade.show{"aria-labelledby" => "first-tab", :role => "tabpanel"}
    %p
    .row
      .col-lg-6
        .card
          .card-header
            .fa.fa-chart-line
            = t('.payments_per_month')
        %p
        = line_chart Expence.all.group_by_month(:created_at).sum("amount/100")
        %p

app/views/dashboard/lead_stats.html.haml
.text-center
  %h5= t('.lead_stats')
.row
  .col-lg-12
    .card
      .card-header
        .fa.fa-chart-line
        = t('.created_per_month')
      .card-body
        = line_chart @leads.group_by_day(:created_at).count, download: true
    %p
.row
  .col-lg-4
    .card
      .card-header
        .fa.fa-chart-line
        = t('.service_popularity')
      .card-body
        = pie_chart @leads.joins(:service).group(:'services.name').count, download: true
    %p
  .col-lg-4
    .card
      .card-header
        .fa.fa-chart-line
        = t('.member_popularity')
      .card-body
        = pie_chart @leads.joins(:member).group(:'members.last_name').count, download: true
    %p
  .col-lg-4
    .card
      .card-header
        .fa.fa-chart-line
        = t('.location_popularity')
      .card-body
        = pie_chart @leads.joins(:location).group(:'locations.name').count, download: true
    %p

app/views/dashboard/member_salary.html.haml
.text-center
  %h5= t('.member_salary')
%hr
= form_tag dashboard_member_salary_path, method: :get do
  - unless params.has_key?(:select)
    .form-inline
      = select_tag :member, options_for_select(@members.map{|c| [c.full_name, c.id]}), { prompt: t('sidebar.members'), onchange: 'this.form.submit()' }
      = select_month(Date.today, {use_two_digit_numbers: true, prefix: 'select'},{:field_name => 'month', :id => 'start-month', onchange: 'this.form.submit()'})
      = select_year(Date.today, {:start_year => DateTime.now.year,:end_year => Tenant.current_tenant.created_at.year, prefix: 'select'},{:field_name => 'year', :id => 'start-year', onchange: 'this.form.submit()'})
  - else
    .form-inline
      = select_tag :member, options_for_select(@members.map{|c| [c.full_name, c.id]}, params[:member]), { prompt: t('sidebar.members'), onchange: 'this.form.submit()' }
      = select_month(@start_date, {use_two_digit_numbers: true, prefix: 'select'},{:field_name => 'month', :id => 'start-month', onchange: 'this.form.submit()'})
      = select_year(@start_date, {:start_year => DateTime.now.year,:end_year => Tenant.current_tenant.created_at.year, prefix: 'select'},{:field_name => 'year', :id => 'start-year', onchange: 'this.form.submit()'})
      = link_to '', dashboard_member_salary_path, class: "btn btn-sm btn-outline-secondary fa fa-redo ml-1"
    %p
    .table-responsive
      %table#table1
        - @member_select.each do |member|
          %thead
            %tr
              %th= link_to member.full_name, member_path(member)
              %th= t('.jobs')
              %th= t('.hours_worked')
              %th= t('.payments')
              %th= t('.expences')
          %thead
            %tr
              %th= t('.confirmed')
              %th= @confirmed_job_q
              %th= @confirmed_hours_worked.round(0)
              %th= @total_confirmed_earnings
              %th= @total_confirmed_expences
          %thead
            %tr
              %th= t('.cancelled')
              %th= @lost_job_q
              %th= @lost_hours_worked.round(0)
              %th= @total_lost_earnings
              %th= @total_lost_expences
    = render 'events/jobs_index'

app/views/dashboard/member_stats.html.haml
.text-center
  %h5= t('.member_stats')
.row
  .col-12
    .card
      .card-header
        = t('.confirmed_jobs_per_month_quantity')
      .card-body
        = line_chart charts_members_jobs_per_member_per_month_quantity_path
    %p
  .col-12
    .card
      .card-header
        = t('.confirmed_jobs_per_month_client_price')
      .card-body
        = line_chart charts_members_confirmed_client_price_per_month_path, prefix: "#{Tenant.current_tenant.default_currency.upcase} "
    %p
  .col-12
    .card
      .card-header
        = t('.confirmed_jobs_per_month_member_price')
      .card-body
        = line_chart charts_members_confirmed_earnings_per_month_path, prefix: "#{Tenant.current_tenant.default_currency.upcase} "
  /  %p
  /.col-12
  /  .card
  /    .card-header
  /      = t('.expences_per_month_amount')
  /    .card-body
  /      = line_chart charts_members_expences_per_month_path, prefix: "#{Tenant.current_tenant.default_currency.upcase} "
%p

app/views/dashboard/transaction_stats.html.haml
.text-center
  %h5= t('.transaction_stats')
%ul#myTab.nav.nav-tabs{:role => "tablist"}
  %li.nav-item
    %a#zero-tab.nav-link.active{"aria-controls" => "zero", "aria-selected" => "true", "data-toggle" => "tab", :href => "#zero", :role => "tab"}
      = t('.per_day')
  %li.nav-item
    %a#first-tab.nav-link{"aria-controls" => "first", "aria-selected" => "true", "data-toggle" => "tab", :href => "#first", :role => "tab"}
      = t('.per_month')
#myTabContent.tab-content
  #zero.tab-pane.fade.show.active{"aria-labelledby" => "zero-tab", :role => "tabpanel"}
    %p
    = form_tag dashboard_transaction_stats_path, method: :get do
      - if params.has_key?(:select)
        = select_month(@start_date, {use_two_digit_numbers: true, prefix: 'select'},{:field_name => 'month', :id => 'start-month', onchange: 'this.form.submit()'})
        = select_year(@start_date, {:start_year => DateTime.now.year,:end_year => Tenant.current_tenant.created_at.year, prefix: 'select'},{:field_name => 'year', :id => 'start-year', onchange: 'this.form.submit()'})
        = link_to t('.current_month'), dashboard_transaction_stats_path, class: "btn  btn-sm btn-secondary"
      - else
        = select_month(Date.today, {use_two_digit_numbers: true, prefix: 'select'},{:field_name => 'month', :id => 'start-month', onchange: 'this.form.submit()'})
        = select_year(Date.today, {:start_year => DateTime.now.year,:end_year => Tenant.current_tenant.created_at.year, prefix: 'select'},{:field_name => 'year', :id => 'start-year', onchange: 'this.form.submit()'})
      /= submit_tag("Search", :id=>"button", :class=>"Test", :name=>"submit")
    %p
    .row
      .col-lg-6
        .card
          .card-header
            .fa.fa-chart-line
            = t('.transactions_per_day')
        .card
          .card-header
            %b= t('.quantity') + ":"
            = @transactions.count
            %b= t('.amount') + ":"
            = @transactions.sum("amount/100")
        %table.table.table-sm.table-bordered
          %tbody
            - @transactions.group_by_day(:created_at).sum("amount/100").each do |k, v|
              %tr
                %td= k.strftime('%d/%m/%Y')
                %td= v
        %p
      .col-lg-6
        .card
          .card-header
            .fa.fa-chart-line
            = t('.transactions_per_day')
          .card-body
            /= bar_chart charts_transactions_per_day_path
            = line_chart @transactions.group_by_day(:created_at).sum("amount/100")
  #first.tab-pane.fade.show{"aria-labelledby" => "first-tab", :role => "tabpanel"}
    %p
    .row
      .col-lg-6
        .card
          .card-header
            .fa.fa-chart-line
            = t('.transactions_per_month')
        %table.table.table-sm.table-bordered
          %tbody
            - Transaction.group_by_month(:created_at).sum("amount/100").each do |k, v|
              %tr
                %td= k.strftime('%m/%Y')
                %td= v
        %p
      .col-lg-6
        .card
          .card-header
            .fa.fa-chart-line
            = t('.transactions_per_month')
          .card-body
            = line_chart charts_transactions_per_month_path
%br