config/routes.rb
Rails.application.routes.draw do
  constraints subdomain: "app" do
    get "static_pages/landing_page"
  end
  # get 'static_pages/pricing', constraints: {subdomain: 'admin'}
  # get 'pricing', to: 'static_pages#pricing', constraints: {subdomain: 'admin'}
  constraints subdomain: "api" do
    scope module: "api" do
      get "static_pages/features"
    end
  end
  # get 'cars', to: 'cars#index'
  # post 'cars', to: 'cars#create'
  # get 'cars/new', to: 'cars#new', as: :new_car
  # get 'cars/:id/edit', to: 'cars#edit', as: :edit_car
  # get 'cars/:id', to: 'cars#show', as: :car
  # put 'cars/:id', to: 'cars#update'
  # patch 'cars/:id', to: 'cars#update'
  # delete 'cars/:id', to: 'cars#destroy'
  # post 'leads/create', to: 'leads#create', as: :create_a_lead

  get "static_pages/landing_page"
  root to: "static_pages#landing_page"
  get "stats", to: "static_pages#stats" # total stats for the superadmin

  get "booking", to: "booking#index"
  get "/booking/:id", to: "booking#show", as: :booking_show
  match "/booking/:id" => "booking#create", :via => [:post], :as => :create
  get "/booking/:id/new", to: "booking#new", as: :new_booking

  # *MUST* come *BEFORE* devise's definitions (below)
  as :user do
    match "/user/confirmation" => "confirmations#update", :via => :put, :as => :update_user_confirmation
  end

  devise_for :users, controllers: {
    registrations: "registrations",
    confirmations: "confirmations",
    sessions: "milia/sessions",
    passwords: "milia/passwords"
  }

  resources :users, only: [:destroy, :edit, :update]
  resources :members do
    get :calendar_list, on: :collection
    member do
      delete :delete_avatar
      get :calendar
    end
  end
  resources :after_signup_wizard

  resources :leads do
    resources :booking_wizard, controller: "leads/booking_wizard"
    member do
      patch :create_client_from_lead
    end
  end

  # edit tenant info
  match "/settings/show" => "tenants#show", :via => :get
  match "/settings/edit" => "tenants#edit", :via => :get, :as => :edit_tenant
  match "/settings/update" => "tenants#update", :via => [:put, :patch], :as => :update_tenant
  match "/plan/edit" => "tenants#edit_plan", :via => :get, :as => :edit_plan

  # contacts google import
  get "contacts/import"
  get "contacts/add_all"
  get "/contacts/:provider/contact_callback" => "contacts#import"
  get "/contacts/failure" => "contacts#failure"
  resources :contacts, except: [:destroy, :create, :new, :edit, :update] do
    member do
      patch :create_client_from_contact, :fill_missing_client_data
    end
  end

  resources :clients do
    get :debtors, :no_gender, :bday_today, :no_events, :untagged, on: :collection
    resources :comments
  end

  resources :service_categories
  resources :services

  resources :locations
  resources :workplaces, only: [:show, :index, :destroy]

  resources :events do
    resources :transactions, except: [:edit, :update]
    get :close, :today, :tomorrow, on: :collection
    member do
      patch :create_duplicate
      patch :mark_planned
      patch :mark_confirmed
      patch :mark_member_cancelled
      patch :mark_client_cancelled
      patch :mark_no_show
      patch :mark_no_show_refunded
      patch :send_email_to_client
      patch :send_email_to_members
    end
  end

  resources :transactions, except: [:edit, :update]
  resources :cash_accounts, except: [:show]

  get "calendar", to: "dashboard#calendar"
  get "activity", to: "dashboard#activity"

  get "dashboard/client_stats"
  get "dashboard/member_stats"
  get "dashboard/event_stats"
  get "dashboard/transaction_stats"
  get "dashboard/lead_stats"
  get "dashboard/member_salary"
  namespace :charts do
    get "monthly_events"
    get "finances_client_due_price_per_month"
    get "members_jobs_per_member_per_month_quantity"
    get "members_confirmed_client_price_per_month"
    get "members_confirmed_earnings_per_month"
    get "transactions_per_day"
    get "transactions_per_month"
    get "events_per_day"
  end
end

app/models/service_category.rb
class ServiceCategory < ApplicationRecord
  #-----------------------gem milia-------------------#
  acts_as_tenant
  #-----------------------gem public_activity-------------------#
  include PublicActivity::Model
  tracked owner: proc { |controller, model| controller.current_user }
  tracked tenant_id: proc { Tenant.current_tenant.id }
  #-----------------------relationships-------------------#
  has_many :services, dependent: :restrict_with_error
  has_many :skills, dependent: :restrict_with_error
  has_many :members, through: :skills
  has_many :jobs, through: :services
  #-----------------------validation-------------------#
  validates_uniqueness_of :name, scope: :tenant_id
  validates :name, presence: true
  validates :name, length: {maximum: 144}
  validates :slug, uniqueness: true
  validates :slug, uniqueness: {case_sensitive: false}
  #-----------------------gem friendly_id-------------------#
  extend FriendlyId
  friendly_id :name, use: :slugged

  def to_s
    name
  end
end

app/controllers/service_categories_controller.rb
class ServiceCategoriesController < ApplicationController
  before_action :set_service_category, only: [:edit, :update, :destroy]

  def index
    @service_categories = ServiceCategory.all.order("updated_at DESC")
  end

  def new
    @service_category = ServiceCategory.new
    # @service_categories = ServiceCategory.order(:name)
    authorize @service_category
  end

  def edit
    authorize @service_category
  end

  def create
    @service_category = ServiceCategory.new(service_category_params)
    authorize @service_category

    respond_to do |format|
      if @service_category.save
        format.html { redirect_to service_categories_path, notice: "Service category was successfully created." }
        format.json { render json: @service_category }
      else
        # @service_categories = ServiceCategory.order(:name)
        format.html { render :new }
        format.json { render json: {errors: @service_category.errors.full_messages} }
      end
    end
  end

  def update
    authorize @service_category
    if @service_category.update(service_category_params)
      redirect_to service_categories_url, notice: "Service category was successfully updated."
    else
      render :edit
    end
  end

  def destroy
    authorize @service_category
    @service_category.destroy
    if @service_category.errors.present?
      redirect_to service_categories_url, alert: "Service Category has associated services or skills. Can not delete."
    else
      redirect_to service_categories_url, notice: "Service Category was successfully destroyed."
    end
  end

  private

  def set_service_category
    @service_category = ServiceCategory.friendly.find(params[:id])
  end

  def service_category_params
    params.require(:service_category).permit(:name)
  end
end

app/helpers/service_categories_helper.rb
module ServiceCategoriesHelper
end

app/views/service_categories/_form.html.haml
-# frozen_string_literal: true
= simple_form_for(@service_category) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?
  .form-inputs
    = f.input :name, input_html: { autocomplete: 'nope' }
  %hr
  .form-actions
    = f.button :submit

app/views/service_categories/edit.html.haml
- model_class = ServiceCategory
.row
  .col-lg-3
  .col-lg-6
    .card
      .card-header#pills-background
        %h5
          .far.fa-hand-paper
          =t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize
      .card-body
        = render 'form'
        %p
        = link_to t('.cancel', :default => t("helpers.links.cancel")), service_categories_path, :class => 'btn btn-danger'

app/views/service_categories/index.haml
- model_class = ServiceCategory
.card
  .card-header
    %h5.float-left
      .fa.fa-hand-paper
      %b=t '.title', :default => model_class.model_name.human.pluralize.titleize
      .badge.badge-info
        = @service_categories.count
    %h5.float-right
      = link_to t('.new', :default => t("helpers.links.new")), new_service_category_path, class: 'btn btn-sm btn-primary'
.table-responsive-xl
  %table#table1
    %thead
      %tr
        %th
          = model_class.human_attribute_name(:name)
        %th
          .fa.fa-hand-paper
          = model_class.human_attribute_name(:services_count)
        %th
          .fa.fa-user-tie
          = model_class.human_attribute_name(:members_count)
        %th
    %tbody
      - @service_categories.each do |service_category|
        %tr
          %td= service_category.name
          %td
            = link_to services_path(q: {service_category_id_eq: service_category.id}) do
              = service_category.services_count
          %td
            = link_to members_path(members_search: {skills_service_category_id_eq: service_category.id}) do
              = service_category.skills.count
          %td
            = link_to '', edit_service_category_path(service_category), class: "btn btn-warning fa fa-edit btn-sm" if policy(service_category).edit?
            = link_to '', service_category, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger fa fa-trash btn-sm" if policy(service_category).destroy?

app/views/service_categories/index.html.haml
- model_class = ServiceCategory
.card#pills-background
  .card-header
    %h5.float-left
      .far.fa-hand-paper
      %b=t '.title', :default => model_class.model_name.human.pluralize.titleize
      .badge.badge-info
        = @service_categories.count
    %h5.float-right
      = link_to t('.new', :default => t("helpers.links.new")), new_service_category_path, class: 'btn btn-sm btn-primary'
%p
.card-columns
  - @service_categories.each do |service_category|
    .card
      .card-header
        .far.fa-hand-paper
        = service_category.name
        .float-right
          .btn-group
            = link_to '', edit_service_category_path(service_category), class: "btn btn-warning fa fa-edit btn-sm" if policy(service_category).edit?
            = link_to '', service_category, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger fa fa-trash btn-sm" if policy(service_category).destroy?
      .card-body
        .fa.fa-hand-paper
        = model_class.human_attribute_name(:services_count) + ':'
        = service_category.services_count
        .row
        .fa.fa-user-tie
        = model_class.human_attribute_name(:members_count) + ':'
        = service_category.skills.count
/.table-responsive-xl
/  %table#table1
/    %thead
/      %tr
/        %th
/        %th= model_class.human_attribute_name(:name)
/        %th
/          .fa.fa-hand-paper
/          = model_class.human_attribute_name(:services_count)
/        %th
/          .fa.fa-user-tie
/          = model_class.human_attribute_name(:members_count)
/    %tbody
/      - @service_categories.each do |service_category|
/        %tr
/          %td
/            .btn-group
/              = link_to '', edit_service_category_path(service_category), class: "btn btn-warning fa fa-edit btn-sm" if policy(service_category).edit?
/              = link_to '', service_category, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger fa fa-trash btn-sm" if policy(service_category).destroy?
/          %td= service_category.name
/          %td= service_category.services_count
/          %td= service_category.skills.count

app/views/service_categories/new.haml
- model_class = ServiceCategory
.row
  .col-lg-3
  .col-lg-6
    .card
      .card-body
        %h5
          .fa.fa-hand-paper
          =t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize
        %hr
        = render 'form'
        %p
        = link_to t('.cancel', :default => t("helpers.links.cancel")), service_categories_path, :class => 'btn btn-danger'

app/views/service_categories/new.html.haml
- model_class = ServiceCategory
.row
  .col-lg-3
  .col-lg-6
    .card
      .card-header#pills-background
        %h5
          .far.fa-hand-paper
          =t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize
      .card-body
        = render 'form'
        %p
        = link_to t('.cancel', :default => t("helpers.links.cancel")), service_categories_path, :class => 'btn btn-danger'