config/routes.rb
Rails.application.routes.draw do
  constraints subdomain: "app" do
    get "static_pages/landing_page"
  end
  # get 'static_pages/pricing', constraints: {subdomain: 'admin'}
  # get 'pricing', to: 'static_pages#pricing', constraints: {subdomain: 'admin'}
  constraints subdomain: "api" do
    scope module: "api" do
      get "static_pages/features"
    end
  end
  # get 'cars', to: 'cars#index'
  # post 'cars', to: 'cars#create'
  # get 'cars/new', to: 'cars#new', as: :new_car
  # get 'cars/:id/edit', to: 'cars#edit', as: :edit_car
  # get 'cars/:id', to: 'cars#show', as: :car
  # put 'cars/:id', to: 'cars#update'
  # patch 'cars/:id', to: 'cars#update'
  # delete 'cars/:id', to: 'cars#destroy'
  # post 'leads/create', to: 'leads#create', as: :create_a_lead

  get "static_pages/landing_page"
  root to: "static_pages#landing_page"
  get "stats", to: "static_pages#stats" # total stats for the superadmin

  get "booking", to: "booking#index"
  get "/booking/:id", to: "booking#show", as: :booking_show
  match "/booking/:id" => "booking#create", :via => [:post], :as => :create
  get "/booking/:id/new", to: "booking#new", as: :new_booking

  # *MUST* come *BEFORE* devise's definitions (below)
  as :user do
    match "/user/confirmation" => "confirmations#update", :via => :put, :as => :update_user_confirmation
  end

  devise_for :users, controllers: {
    registrations: "registrations",
    confirmations: "confirmations",
    sessions: "milia/sessions",
    passwords: "milia/passwords"
  }

  resources :users, only: [:destroy, :edit, :update]
  resources :members do
    get :calendar_list, on: :collection
    member do
      delete :delete_avatar
      get :calendar
    end
  end
  resources :after_signup_wizard

  resources :leads do
    resources :booking_wizard, controller: "leads/booking_wizard"
    member do
      patch :create_client_from_lead
    end
  end

  # edit tenant info
  match "/settings/show" => "tenants#show", :via => :get
  match "/settings/edit" => "tenants#edit", :via => :get, :as => :edit_tenant
  match "/settings/update" => "tenants#update", :via => [:put, :patch], :as => :update_tenant
  match "/plan/edit" => "tenants#edit_plan", :via => :get, :as => :edit_plan

  # contacts google import
  get "contacts/import"
  get "contacts/add_all"
  get "/contacts/:provider/contact_callback" => "contacts#import"
  get "/contacts/failure" => "contacts#failure"
  resources :contacts, except: [:destroy, :create, :new, :edit, :update] do
    member do
      patch :create_client_from_contact, :fill_missing_client_data
    end
  end

  resources :clients do
    get :debtors, :no_gender, :bday_today, :no_events, :untagged, on: :collection
    resources :comments
  end

  resources :service_categories
  resources :services

  resources :locations
  resources :workplaces, only: [:show, :index, :destroy]

  resources :events do
    resources :transactions, except: [:edit, :update]
    get :close, :today, :tomorrow, on: :collection
    member do
      patch :create_duplicate
      patch :mark_planned
      patch :mark_confirmed
      patch :mark_member_cancelled
      patch :mark_client_cancelled
      patch :mark_no_show
      patch :mark_no_show_refunded
      patch :send_email_to_client
      patch :send_email_to_members
    end
  end

  resources :transactions, except: [:edit, :update]
  resources :cash_accounts, except: [:show]

  get "calendar", to: "dashboard#calendar"
  get "activity", to: "dashboard#activity"

  get "dashboard/client_stats"
  get "dashboard/member_stats"
  get "dashboard/event_stats"
  get "dashboard/transaction_stats"
  get "dashboard/lead_stats"
  get "dashboard/member_salary"
  namespace :charts do
    get "monthly_events"
    get "finances_client_due_price_per_month"
    get "members_jobs_per_member_per_month_quantity"
    get "members_confirmed_client_price_per_month"
    get "members_confirmed_earnings_per_month"
    get "transactions_per_day"
    get "transactions_per_month"
    get "events_per_day"
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :authenticate_tenant!, :only => [ :landing_page ]

  def landing_page
    if current_user
      redirect_to calendar_path
    end
  end

  def activity
    @activities = PublicActivity::Activity.paginate(:page => params[:page], :per_page => 100).order("created_at DESC")
  end

  def start
  end

  def calendar
    @jobs = Job.includes(:event, :service, :event => :client)
    @members = Member.active
    #@events = Event.includes(:client, :jobs, :jobs => [:service, :member])
  end

  #def my_calendar
  #  @jobs = Job.where(member_id: current_user.member.id).includes(:event, :service, :member, :event => :client)
  #end
end

app/views/home/dashboard.haml
- set_var 'jobs', Job.where(member_id: current_user.member.id).map{|e| {title: e.location.to_s  + "/" + e.service_name.to_s  + "/" + e.client.full_name.to_s, start: e.starts_at, end: e.ends_at, url: job_path(e), color: e.color}}

.card
  .card-header
    .fa.fa-rocket
    Getting started
  .card-body
    %h5
      = link_to 'update your company settings', edit_plan_path
      %hr
      = link_to 'update your personal info', edit_member_path(current_user.member)
      %hr
      - if Tenant.current_tenant.plan != 'free'
        - unless Member.count >= 2
          %span.badge.badge-pill.badge-danger 0
          = link_to "Invite Employees to your organization", new_member_path
        - else
          %span.badge.badge-pill.badge-success 0
          %del
            Invite Employees to your organization
        %hr
      - unless Location.any?
        %span.badge.badge-pill.badge-danger 1
        = link_to 'Add a Location', new_location_path
      - else
        %span.badge.badge-pill.badge-success 1
        %del
          Add a Location
      %hr
      - unless Service.any?
        %span.badge.badge-pill.badge-danger 2
        = link_to 'Add a Service', new_service_path
      - else
        %span.badge.badge-pill.badge-success 2
        %del
          Add a Service
      %hr
      - unless Client.any?
        %span.badge.badge-pill.badge-danger 3
        = link_to 'Add a Client', new_client_path
      - else
        %span.badge.badge-pill.badge-success 3
        %del
          Add a Client
      %hr
      - unless Job.any?
        .fa.fa-times-circle{:style => "color:red"}

        = link_to 'Add a Job', new_job_path
      - else
        .fa.fa-check-circle{:style => "color:green"}
        %del
          Add a Job
/%p
/.row
/  .col-xl-4
/    .card
/      .card-header
/        .fa.fa-chart-line
/        New Jobs in the last 30 days
/      .card-body
/        = Job.where('created_at >= ?', 1.month.ago).count
/    %p
/  .col-xl-4
/    .card
/      .card-header
/        .fa.fa-chart-line
/        New Clients in the last 30 days
/      .card-body
/        = Client.where('created_at >= ?', 1.month.ago).count
/    %p
/  .col-xl-4
/    .card
/      .card-header
/        .fa.fa-chart-line
/        Turnover in the last 30 days
/      .card-body
/        = number_to_currency(@total_confirmed_earnings, :unit => "$")
%p
.row
  .col-xl-4
    .card-header
      .fa.fa-calendar
      Calendar
      .float-right
        = link_to "more", calendar_path, class: 'btn btn-sm btn-primary'
    .card
      #dailycalendar
      -  Job.all.where(member: current_user.member).where("starts_at > ?", Time.zone.now-15.minutes).limit(5).each do |job|

        /%li.list-group-item
        /  = link_to '', job, class: "btn btn-success fa fa-eye btn-sm", title: 'Show', 'data-toggle' => 'tooltip', 'data-placement' => 'top'
        /  #{job.starts_at.strftime('%d/%b/%Y %H:%M')}
        /  = job.client
        /  = job.service
    %p
  .col-xl-4
    .card-header
      .fa.fa-calendar-check
      Mark Status
      .float-right
        = link_to "#{Job.mark_attendance.count} Tasks", mark_attendance_jobs_path, class: 'btn btn-sm btn-primary'
    .card
      = render 'jobs/index'
    %p
  .col-xl-4
    .card-header
      .fa.fa-bell
      Activity
      .float-right
        = link_to 'more', activity_path, class: 'btn btn-sm btn-primary'
    .card
      =  render 'home/activity'

app/views/home/user_roles.haml
User types:
Admin
Manager
Specialist
Client
Viewer
Owner

%table.table.table-bordered
  %thead
    %tr
      %th 
      %th Index
      %th Show
      %th Create
      %th Edit
      %th Delete
  %tbody
    %tr
      %th{:scope => "row"} Jobs
      %td
      %td
      %td
      %td
      %td
  %tbody
    %tr
      %th{:scope => "row"} Clients
      %td
      %td
      %td
      %td
      %td
  %tbody
    %tr
      %th{:scope => "row"} Employees
      %td
      %td
      %td
      %td
      %td
  %tbody
    %tr
      %th{:scope => "row"} Services
      %td #{'anybody'.humanize}
      %td #{'admin_or_manager'.humanize}
      %td #{'admin_or_manager'.humanize}
      %td #{'admin_or_manager'.humanize}
      %td #{'admin_or_manager'.humanize}
  %tbody
    %tr
      %th{:scope => "row"} Locations
      %td #{'anybody'.humanize}
      %td #{'admin'.humanize}
      %td #{'admin'.humanize}
      %td #{'admin'.humanize}
      %td #{'admin'.humanize}
  %tbody
    %tr
      %th{:scope => "row"} Service_categories
      %td #{'anybody'.humanize}
      %td N/A
      %td #{'admin_or_manager'.humanize}
      %td #{'admin'.humanize}
      %td #{'admin'.humanize}
  %tbody
    %tr
      %th{:scope => "row"} User_roles
      %td
      %td
      %td
      %td
      %td
  %tbody
    %tr
      %th{:scope => "row"} Activity
      %td
      %td
      %td
      %td
      %td
  %tbody
    %tr
      %th{:scope => "row"} Stats
      %td
      %td
      %td
      %td
      %td
  %tbody
    %tr
      %th{:scope => "row"} Role_description
      %td
      %td
      %td
      %td
      %td
%br