config/routes.rb
Rails.application.routes.draw do
  constraints subdomain: "app" do
    get "static_pages/landing_page"
  end
  # get 'static_pages/pricing', constraints: {subdomain: 'admin'}
  # get 'pricing', to: 'static_pages#pricing', constraints: {subdomain: 'admin'}
  constraints subdomain: "api" do
    scope module: "api" do
      get "static_pages/features"
    end
  end
  # get 'cars', to: 'cars#index'
  # post 'cars', to: 'cars#create'
  # get 'cars/new', to: 'cars#new', as: :new_car
  # get 'cars/:id/edit', to: 'cars#edit', as: :edit_car
  # get 'cars/:id', to: 'cars#show', as: :car
  # put 'cars/:id', to: 'cars#update'
  # patch 'cars/:id', to: 'cars#update'
  # delete 'cars/:id', to: 'cars#destroy'
  # post 'leads/create', to: 'leads#create', as: :create_a_lead

  get "static_pages/landing_page"
  root to: "static_pages#landing_page"
  get "stats", to: "static_pages#stats" # total stats for the superadmin

  get "booking", to: "booking#index"
  get "/booking/:id", to: "booking#show", as: :booking_show
  match "/booking/:id" => "booking#create", :via => [:post], :as => :create
  get "/booking/:id/new", to: "booking#new", as: :new_booking

  # *MUST* come *BEFORE* devise's definitions (below)
  as :user do
    match "/user/confirmation" => "confirmations#update", :via => :put, :as => :update_user_confirmation
  end

  devise_for :users, controllers: {
    registrations: "registrations",
    confirmations: "confirmations",
    sessions: "milia/sessions",
    passwords: "milia/passwords"
  }

  resources :users, only: [:destroy, :edit, :update]
  resources :members do
    get :calendar_list, on: :collection
    member do
      delete :delete_avatar
      get :calendar
    end
  end
  resources :after_signup_wizard

  resources :leads do
    resources :booking_wizard, controller: "leads/booking_wizard"
    member do
      patch :create_client_from_lead
    end
  end

  # edit tenant info
  match "/settings/show" => "tenants#show", :via => :get
  match "/settings/edit" => "tenants#edit", :via => :get, :as => :edit_tenant
  match "/settings/update" => "tenants#update", :via => [:put, :patch], :as => :update_tenant
  match "/plan/edit" => "tenants#edit_plan", :via => :get, :as => :edit_plan

  # contacts google import
  get "contacts/import"
  get "contacts/add_all"
  get "/contacts/:provider/contact_callback" => "contacts#import"
  get "/contacts/failure" => "contacts#failure"
  resources :contacts, except: [:destroy, :create, :new, :edit, :update] do
    member do
      patch :create_client_from_contact, :fill_missing_client_data
    end
  end

  resources :clients do
    get :debtors, :no_gender, :bday_today, :no_events, :untagged, on: :collection
    resources :comments
  end

  resources :service_categories
  resources :services

  resources :locations
  resources :workplaces, only: [:show, :index, :destroy]

  resources :events do
    resources :transactions, except: [:edit, :update]
    get :close, :today, :tomorrow, on: :collection
    member do
      patch :create_duplicate
      patch :mark_planned
      patch :mark_confirmed
      patch :mark_member_cancelled
      patch :mark_client_cancelled
      patch :mark_no_show
      patch :mark_no_show_refunded
      patch :send_email_to_client
      patch :send_email_to_members
    end
  end

  resources :transactions, except: [:edit, :update]
  resources :cash_accounts, except: [:show]

  get "calendar", to: "dashboard#calendar"
  get "activity", to: "dashboard#activity"

  get "dashboard/client_stats"
  get "dashboard/member_stats"
  get "dashboard/event_stats"
  get "dashboard/transaction_stats"
  get "dashboard/lead_stats"
  get "dashboard/member_salary"
  namespace :charts do
    get "monthly_events"
    get "finances_client_due_price_per_month"
    get "members_jobs_per_member_per_month_quantity"
    get "members_confirmed_client_price_per_month"
    get "members_confirmed_earnings_per_month"
    get "transactions_per_day"
    get "transactions_per_month"
    get "events_per_day"
  end
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  before_action :set_transaction, only: [:show, :destroy]
  include Pagy::Backend

  def index
    @q = Transaction.ransack(params[:q])
    @pagy, @transactions = pagy(@q.result.order("created_at DESC"))
  end

  def show
    authorize @transaction
    @activities = PublicActivity::Activity.order("created_at DESC").where(trackable_type: "Transaction", trackable_id: @transaction).all
    respond_to do |format|
      format.html
      format.pdf do
        render pdf: "Payment No. #{@transaction.slug}",
               page_size: "A6",
               template: "transactions/show.pdf.haml",
               # template: "transactions/transaction_pdf.html.haml",
               # template: "transactions/show.html.haml",
               # format.pdf {render template: "payments/report", pdf: 'report'}   # Excluding ".pdf" extension.
               # format.pdf {render template: "projects/report", pdf: "invoice #{@project.id}"}
               layout: "pdf.html.haml",
               orientation: "Portrait",
               lowquality: true,
               zoom: 1,
               dpi: 75
      end
    end
  end

  def new
    @transaction = Transaction.new
    @cash_accounts = CashAccount.order("created_at ASC")
    @clients = Client.all
    authorize @transaction
  end

  def create
    @transaction = Transaction.new(transaction_params)
    authorize @transaction
    respond_to do |format|
      if @transaction.save
        if @transaction.payable_id.present?
          format.html { redirect_to @transaction.payable, notice: "Payment was successfully created." }
        else
          format.html { redirect_to @transaction.client, notice: "Payment was successfully created." }
          format.json { render :show, status: :created, location: @transaction }
        end
      else
        @clients = Client.all
        @cash_accounts = CashAccount.order("created_at ASC")
        format.html { render :new }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    authorize @transaction
    @transaction.destroy
    if @transaction.payable_id.present?
      redirect_to @transaction.payable, notice: "Payment was successfully destroyed."
    else
      respond_to do |format|
        format.html { redirect_to @transaction.client, notice: "Payment was successfully destroyed." }
        format.json { head :no_content }
      end
    end
  end

  private

  def set_transaction
    @transaction = Transaction.friendly.find(params[:id])
  end

  def transaction_params
    params.require(:transaction).permit(:tenant_id, :cash_account_id,
      :amount, :amount_cents,
      :payable_id, :payable_type,
      :comment)
  end
end

app/views/transactions/_form.html.haml
-# frozen_string_literal: true
= simple_form_for(@transaction) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?
  .form-inputs
    = f.association :cash_account, as: :radio_buttons, label_method: :full_name, collection: @cash_accounts
    - if @client.present?
      = f.input :payable_type, input_html: {value: "Client"}, as: :hidden
      = f.input :payable_id, input_html: {value: @client.id}, as: :hidden
    - else
      = f.input :payable_type, input_html: {value: "Client"}, as: :hidden
      /= f.label :member
      /= f.label :client
      = f.label :payable_type
      = f.select :payable_id, @clients.map{|c| [c.full_name, c.id]}, {include_blank: true}, class: 'selectize'
      = f.error :payable_id, class: 'text-danger'
      /= f.input :payable_id, collection: @clients, class: 'selectize'
      /= f.input :payable_id, collection: @clients, input_html: { class: 'selectize' }

    = f.input :amount_cents, input_html: { value: '', autocomplete: 'off' }, placeholder: "0"
    /= f.input :amount_cents, input_html: { autocomplete: 'off' }, placeholder: "0"
    = f.input :comment
  %hr
  .form-actions
    = f.button :submit

app/views/transactions/_index.haml
- model_class = Transaction
%thead
  %tr
    %th
    /for nesting in clients/show
    - if @q.present?
      %th= sort_link @q, :id, model_class.human_attribute_name(:id)
      %th= sort_link @q, :amount, model_class.human_attribute_name(:amount_cents)
      %th= sort_link @q, :cash_account_name, model_class.human_attribute_name(:cash_account)
      %th= sort_link @q, :type, model_class.human_attribute_name(:comment)
      %th= sort_link @q, :payable_type, model_class.human_attribute_name(:payable_type)
      %th= sort_link @q, :payable_id, model_class.human_attribute_name(:payable_id)
      %th= sort_link @q, :created_at, model_class.human_attribute_name(:created_at)
    - else
      %th= model_class.human_attribute_name(:id)
      %th= model_class.human_attribute_name(:amount_cents)
      %th= model_class.human_attribute_name(:cash_account)
      %th= model_class.human_attribute_name(:comment)
      %th= model_class.human_attribute_name(:payable_type)
      %th= model_class.human_attribute_name(:payable_id)
      %th= model_class.human_attribute_name(:created_at)
- @transactions.each do |transaction|
  %tbody
    %tr
      %td
        .btn-group
          = link_to "", transaction_path(transaction, format: :pdf), class: "btn btn-primary fa fa-file-pdf btn-sm", target: :_blank
          = link_to '', transaction, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger fa fa-trash btn-sm" if policy(transaction).destroy?          
      %td= link_to transaction.slug, transaction_path(transaction)
      %td= transaction.amount_cents
      %td= transaction.cash_account
      %td= transaction.comment
      %td= transaction.payable_type
      %td
        = link_to transaction.payable, polymorphic_url(transaction.payable) if transaction.payable.present?
      %td= l(transaction.created_at, format: "%a %d/%b/%Y %H:%M")

app/views/transactions/_index.html.haml
- model_class = Transaction
%thead
  %tr
    %th
    /for nesting in clients/show
    - if @q.present?
      %th= sort_link @q, :id, model_class.human_attribute_name(:id)
      %th= sort_link @q, :amount, model_class.human_attribute_name(:amount_cents)
      %th= sort_link @q, :cash_account_name, model_class.human_attribute_name(:cash_account)
      %th= sort_link @q, :type, model_class.human_attribute_name(:comment)
      %th= sort_link @q, :payable_type, model_class.human_attribute_name(:payable_type)
      %th= sort_link @q, :payable_id, model_class.human_attribute_name(:payable_id)
      %th= sort_link @q, :created_at, model_class.human_attribute_name(:created_at)
    - else
      %th= model_class.human_attribute_name(:id)
      %th= model_class.human_attribute_name(:amount_cents)
      %th= model_class.human_attribute_name(:cash_account)
      %th= model_class.human_attribute_name(:comment)
      %th= model_class.human_attribute_name(:payable_type)
      %th= model_class.human_attribute_name(:payable_id)
      %th= model_class.human_attribute_name(:created_at)
- @transactions.each do |transaction|
  %tbody
    %tr
      %td
        .btn-group
          = link_to "", transaction_path(transaction, format: :pdf), class: "btn btn-primary fa fa-file-pdf btn-sm", target: :_blank
          = link_to '', transaction, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger fa fa-trash btn-sm" if policy(transaction).destroy?          
      %td= link_to transaction.slug, transaction_path(transaction)
      %td= transaction.amount_cents
      %td= transaction.cash_account
      %td= transaction.comment
      %td= transaction.payable_type
      %td
        = link_to transaction.payable, polymorphic_url(transaction.payable) if transaction.payable.present?
      %td= l(transaction.created_at, format: "%a %d/%b/%Y %H:%M")

app/views/transactions/_polymorphic_form.haml
= simple_form_for [@payable, @payment] do |f|
  - if @payment.errors.any?
    .error_messages
      %h2 Please correct the following errors.
      %ul
        - @payment.errors.full_messages.each do |msg|
          %li= msg
  /.field
  /  = f.input :client_id, input_html: {value: @event.client.id}, as: :hidden
  /  = f.input :amount_cents, input_html: {value: @event.client_price_to_pay_cents}, as: :hidden
  .actions
    = f.submit

app/views/transactions/_polymorphic_form.html.haml
= simple_form_for [@payable, @payment] do |f|
  - if @payment.errors.any?
    .error_messages
      %h2 Please correct the following errors.
      %ul
        - @payment.errors.full_messages.each do |msg|
          %li= msg
  /.field
  /  = f.input :client_id, input_html: {value: @event.client.id}, as: :hidden
  /  = f.input :amount_cents, input_html: {value: @event.client_price_to_pay_cents}, as: :hidden
  .actions
    = f.submit

app/views/transactions/index.html.haml
- model_class = Transaction
= search_form_for @q, url: transactions_path do |f|
  .card#pills-background
    .card-header
      %h5.float-left
        .fa.fa-exchange-alt
        %b=t '.title', :default => model_class.model_name.human.pluralize.titleize
        .badge.badge-info
          = @transactions.count
      %h5.float-right
        - if params.has_key?(:q)
          = link_to "", transactions_path, class: "btn btn-secondary fa fa-redo", title: 'Refresh', 'data-toggle' => 'tooltip', 'data-placement' => 'top'
        = link_to t('.new', :default => t("helpers.links.new")), new_transaction_path, class: 'btn btn-sm btn-primary'
.table-responsive
= search_form_for @q, url: transactions_path do |f|
  %table#table1
    %thead
      %tr
        %th= f.submit
        %th= f.text_field :slug_cont, class: "form-control-sm", placeholder: model_class.human_attribute_name(:id), style: 'float: left; width: 100%; display: block'
        %th
        %th= f.select :cash_account_id_eq, options_from_collection_for_select(CashAccount.all, :id, :name, @q.cash_account_id_eq), { :include_blank => true }, :class => "form-control-sm", style: 'width: 120px'
        %th
        %th
        %th
        %th
          = f.date_field :created_at_gteq, class: 'form-control-sm'
          = f.hidden_field :created_at_datelteq
    = render 'transactions/index'
.container.table-responsive
  != pagy_bootstrap_nav(@pagy)
%br

app/views/transactions/new.html.haml
- model_class = Transaction
.row
  .col-lg-3
  .col-lg-6
    .card
      .card-header#pills-background
        %h5
          .fa.fa-hand-holding-usd
          =t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize
      .card-body
        = render 'form'
        %p
        = link_to t('.cancel', :default => t("helpers.links.cancel")), transactions_path, :class => 'btn btn-danger'

app/views/transactions/show.html.haml
- model_class = Transaction
.row
  .col-md-3
  .col-md-6
    .row
      .container
        .card
          .card-header
            .fa.fa-exchange-alt
            =t '.title', :default => model_class.model_name.human.titleize
            .float-right
              .btn-group
                = link_to "", transaction_path(@transaction, format: :pdf), class: "btn btn-primary fa fa-file-pdf btn-sm", target: :_blank
                = link_to '', @transaction, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger fa fa-trash btn-sm" if policy(@transaction).destroy?
          .card-body
            %b= model_class.human_attribute_name(:id)
            = link_to @transaction.slug, transaction_path(@transaction)
            .row
            %b= model_class.human_attribute_name(:amount_cents)
            = @transaction.amount_cents
            .row
            %b= model_class.human_attribute_name(:cash_account)
            = @transaction.cash_account
            .row
            %b= model_class.human_attribute_name(:comment)
            = @transaction.comment
            .row
            %b= model_class.human_attribute_name(:payable_type)
            = @transaction.payable_type
            .row
            %b= model_class.human_attribute_name(:payable_id)
            = link_to @transaction.payable, polymorphic_url(@transaction.payable) if @transaction.payable.present?
            .row
            %b= model_class.human_attribute_name(:created_at)
            = l(@transaction.created_at, format: "%a %d/%b/%Y %H:%M")
    %p
    =  render 'dashboard/activity'

app/views/transactions/show.pdf.haml
- model_class = Transaction
.row
  .container
    .card
      .card-header
        =t '.title', :default => model_class.model_name.human.titleize
      .card-body
        %b= model_class.human_attribute_name(:id)
        = link_to @transaction.slug, transaction_path(@transaction)
        .row
        %b= model_class.human_attribute_name(:amount_cents)
        = @transaction.amount_cents
        .row
        %b= model_class.human_attribute_name(:cash_account)
        = @transaction.cash_account
        .row
        %b= model_class.human_attribute_name(:comment)
        = @transaction.comment
        .row
        %b= model_class.human_attribute_name(:payable_type)
        = @transaction.payable_type
        .row
        %b= model_class.human_attribute_name(:payable_id)
        = link_to @transaction.payable, polymorphic_url(@transaction.payable) if @transaction.payable.present?
        .row
        %b= model_class.human_attribute_name(:created_at)
        = l(@transaction.created_at, format: "%a %d/%b/%Y %H:%M")
        %br
        - @activities.each do |a|
          %b= model_class.human_attribute_name(:created_at) + ':'
          #{l(a.created_at, format: "%d/%b/%Y %H:%M")}
          .row
          %b= t('member') + ':'
          = link_to a.owner.to_s, member_path(a.owner.member.id) if a.owner.member